# Generated by Django 4.2.29 on 2026-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="image_url",
        ),
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
